// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3E9LRX7HaMwmHyiEEz7m5N4L5-aihXi0',
    appId: '1:1020887459856:web:382fa740827ad145e6c295',
    messagingSenderId: '1020887459856',
    projectId: 'mochimind-f06eb',
    authDomain: 'mochimind-f06eb.firebaseapp.com',
    storageBucket: 'mochimind-f06eb.firebasestorage.app',
    measurementId: 'G-EDVCY0V3G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAvhlcfHezZTXY_iq0UzbXW44kmHDDEA',
    appId: '1:1020887459856:android:d6953f70b9b4f515e6c295',
    messagingSenderId: '1020887459856',
    projectId: 'mochimind-f06eb',
    storageBucket: 'mochimind-f06eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkykWwcRyaHy4i8iCZfuWCwKjHhj85kZU',
    appId: '1:1020887459856:ios:3a2e76886032093ce6c295',
    messagingSenderId: '1020887459856',
    projectId: 'mochimind-f06eb',
    storageBucket: 'mochimind-f06eb.firebasestorage.app',
    iosBundleId: 'com.example.mochiMindSp',
  );
}
